%YAML 1.2
---
# AlgoLogin Config
server_ip: "119.3.103.38"
server_port: 6002
username: "253191000198"
password: "RnancU1F"
local_ip: "127.0.0.1"
#templete localip

#AlgoConfig
AlgoConfig: Config/AlgoConfig.yaml
