%YAML 1.2
---
# AlgoLogin Config

server_ip: "119.3.40.4"
server_port: 8602
username: "315011679"
password: "123456"
algo_local_ip: "127.0.0.1"
algo_log_level: 3
algo_config_file: Config/AlgoConfig.yaml
