%YAML 1.2
---
#TDF information
Test: 
 server_ip: "119.3.103.38"
 server_port: 6002
 username: "253191000198"
 password: "RnancU1F"
 client_id: 3
 path_linux: "/root/log/"
 path: "D:\\test\\"
 exchange_id_sh: 1
 exchange_id_sz: 2
 query_tickers_path_sh: "tickers_sh.txt"
 query_tickers_path_sz: "tickers_sz.txt"
 instrument_sh:
  - "688281"
  - "603070"
 instrument_sz:
  - "000004"
  - "301222"
 hb_interval: 15
 quote_buffer_size: 128
 quote_protocol: 1