%YAML 1.2
---
#XTPTrade information
# side,price_type use ASCII
Test: 
 server_ip: "122.112.139.0"
 server_port: 6102
 username: "253191000198"
 password: "RnancU1F"
 local_ip: "192.168.0.204"
 tokenkey: "b8aa7173bba3470e390d787219b2112e"
 client_id: 3
 path_linux: "/root/log/"
 path: "./test"
 exchange_id_sh: 1
 exchange_id_sz: 2
 order:
  -
    client_order_id: 1
    instrument_id: 688001
    price: 22.20
    quantity: 200
    side: 66
    price_type: 76
 cancel_order_id: 
 query_position_is_true: true
 query_position_is_all: true
 query_position_instrument: 688001
 query_balance_is_true_account: true
 query_balance_is_true_broker: true
 hb_interval: 15
 quote_buffer_size: 128
 quote_protocol: 1